import type { BlockConfig, BlockType } from './types';

export const BLOCK_CONFIGS: Record<BlockType, BlockConfig> = {
  move: {
    type: 'move',
    label: '前进',
    color: 'bg-block-move',
    icon: '➡️',
    description: '机器人向前移动一格',
    category: 'basic',
  },
  turnLeft: {
    type: 'turnLeft',
    label: '左转',
    color: 'bg-block-turn',
    icon: '↪️',
    description: '机器人向左转90度',
    category: 'basic',
  },
  turnRight: {
    type: 'turnRight',
    label: '右转',
    color: 'bg-block-turn',
    icon: '↩️',
    description: '机器人向右转90度',
    category: 'basic',
  },
  loop: {
    type: 'loop',
    label: '循环',
    color: 'bg-block-loop',
    icon: '🔄',
    description: '重复执行内部指令指定次数',
    category: 'control',
    hasChildren: true,
    canRepeat: true,
  },
  ifWall: {
    type: 'ifWall',
    label: '如果前方是墙',
    color: 'bg-block-condition',
    icon: '🧱',
    description: '如果前方有墙壁，则执行内部指令',
    category: 'condition',
    hasChildren: true,
  },
  ifStar: {
    type: 'ifStar',
    label: '如果前方有星星',
    color: 'bg-block-condition',
    icon: '⭐',
    description: '如果前方有星星，则执行内部指令',
    category: 'condition',
    hasChildren: true,
  },
  ifEmpty: {
    type: 'ifEmpty',
    label: '如果前方是空',
    color: 'bg-block-condition',
    icon: '⬜',
    description: '如果前方可以通行，则执行内部指令',
    category: 'condition',
    hasChildren: true,
  },
  function: {
    type: 'function',
    label: '定义函数',
    color: 'bg-block-function',
    icon: '📦',
    description: '定义一个可重复调用的函数',
    category: 'function',
    hasChildren: true,
  },
  callFunction: {
    type: 'callFunction',
    label: '调用函数',
    color: 'bg-block-function',
    icon: '🔧',
    description: '调用已定义的函数',
    category: 'function',
  },
};

export const CATEGORY_NAMES: Record<string, string> = {
  basic: '基础指令',
  control: '流程控制',
  condition: '条件判断',
  function: '函数',
};
