import type { BlockType, CellType, Level } from './types';

function makeGrid(
  width: number,
  height: number,
  walls: [number, number][] = [],
  pits: [number, number][] = []
): CellType[][] {
  const grid: CellType[][] = [];
  for (let y = 0; y < height; y++) {
    const row: CellType[] = [];
    for (let x = 0; x < width; x++) {
      let cell: CellType = 'empty';
      if (walls.some(([wx, wy]) => wx === x && wy === y)) cell = 'wall';
      if (pits.some(([px, py]) => px === x && py === y)) cell = 'pit';
      row.push(cell);
    }
    grid.push(row);
  }
  return grid;
}

const ALL_BLOCKS: BlockType[] = [
  'move',
  'turnLeft',
  'turnRight',
  'loop',
  'ifWall',
  'ifStar',
  'ifEmpty',
  'function',
  'callFunction',
];

const BASIC_BLOCKS: BlockType[] = ['move', 'turnLeft', 'turnRight'];
const BASIC_LOOP: BlockType[] = ['move', 'turnLeft', 'turnRight', 'loop'];
const CONDITION_BLOCKS: BlockType[] = [
  'move',
  'turnLeft',
  'turnRight',
  'loop',
  'ifWall',
  'ifStar',
  'ifEmpty',
];
const FUNCTION_BLOCKS: BlockType[] = [
  'move',
  'turnLeft',
  'turnRight',
  'loop',
  'ifWall',
  'ifEmpty',
  'function',
  'callFunction',
];

export const LEVELS: Level[] = [
  {
    id: 'level-1',
    name: '第1关：第一步',
    description: '让机器人走到终点。使用"前进"指令。',
    difficulty: 1,
    width: 5,
    height: 5,
    grid: makeGrid(5, 5),
    start: { x: 0, y: 2 },
    startDirection: 1,
    goal: { x: 4, y: 2 },
    stars: [],
    allowedBlocks: BASIC_BLOCKS,
    hint: '连续使用4次"前进"指令即可完成。',
  },
  {
    id: 'level-2',
    name: '第2关：转个弯',
    description: '学习转弯指令，先右转再前进。',
    difficulty: 1,
    width: 5,
    height: 5,
    grid: makeGrid(5, 5),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 2, y: 2 },
    stars: [],
    allowedBlocks: BASIC_BLOCKS,
    hint: '向右走2步，右转（向下），再走2步。',
  },
  {
    id: 'level-3',
    name: '第3关：左转也会',
    description: '先前进，再左转，到达终点。',
    difficulty: 1,
    width: 5,
    height: 5,
    grid: makeGrid(5, 5),
    start: { x: 0, y: 4 },
    startDirection: 1,
    goal: { x: 3, y: 1 },
    stars: [],
    allowedBlocks: BASIC_BLOCKS,
    hint: '向右走3步，左转（向上），再走3步。',
  },
  {
    id: 'level-4',
    name: '第4关：S型路线',
    description: '使用多个转弯指令绕过空白。',
    difficulty: 1,
    width: 6,
    height: 5,
    grid: makeGrid(6, 5),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 5, y: 4 },
    stars: [],
    allowedBlocks: BASIC_BLOCKS,
    hint: '右5→右→下4→到达。思考转弯的组合。',
  },
  {
    id: 'level-5',
    name: '第5关：第一颗星',
    description: '收集所有星星后到达终点！',
    difficulty: 2,
    width: 5,
    height: 5,
    grid: makeGrid(5, 5),
    start: { x: 0, y: 2 },
    startDirection: 1,
    goal: { x: 4, y: 2 },
    stars: [{ x: 2, y: 2 }],
    allowedBlocks: BASIC_BLOCKS,
    hint: '向右走4步，星星在中间会自动收集。',
  },
  {
    id: 'level-6',
    name: '第6关：绕墙走',
    description: '墙壁挡路了，绕道而过。',
    difficulty: 2,
    width: 5,
    height: 5,
    grid: makeGrid(5, 5, [
      [2, 1],
      [2, 2],
      [2, 3],
    ]),
    start: { x: 0, y: 2 },
    startDirection: 1,
    goal: { x: 4, y: 2 },
    stars: [],
    allowedBlocks: BASIC_BLOCKS,
    hint: '上→右→下→右→下→右，绕过墙壁。',
  },
  {
    id: 'level-7',
    name: '第7关：两颗星星',
    description: '收集两颗星星，然后到达终点。',
    difficulty: 2,
    width: 5,
    height: 5,
    grid: makeGrid(5, 5),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 4, y: 4 },
    stars: [
      { x: 4, y: 0 },
      { x: 0, y: 4 },
    ],
    allowedBlocks: BASIC_BLOCKS,
    hint: '右4→下4→左4→下不行。想想更高效的路线。',
  },
  {
    id: 'level-8',
    name: '第8关：迷宫入门',
    description: '简单的迷宫，找到正确路径。',
    difficulty: 2,
    width: 6,
    height: 6,
    grid: makeGrid(6, 6, [
      [1, 1],
      [2, 1],
      [3, 1],
      [3, 2],
      [3, 3],
      [1, 3],
      [2, 3],
      [1, 4],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 5, y: 5 },
    stars: [],
    allowedBlocks: BASIC_BLOCKS,
    hint: '寻找通道，注意转弯时机。',
  },
  {
    id: 'level-9',
    name: '第9关：回字形',
    description: '走一个回字形路线。',
    difficulty: 2,
    width: 5,
    height: 5,
    grid: makeGrid(5, 5),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 1, y: 1 },
    stars: [
      { x: 4, y: 0 },
      { x: 4, y: 4 },
      { x: 0, y: 4 },
    ],
    allowedBlocks: BASIC_BLOCKS,
    hint: '沿着外围走一圈，收集所有星星。',
  },
  {
    id: 'level-10',
    name: '第10关：初次循环',
    description: '使用循环指令让代码更简洁！',
    difficulty: 3,
    width: 7,
    height: 5,
    grid: makeGrid(7, 5),
    start: { x: 0, y: 2 },
    startDirection: 1,
    goal: { x: 6, y: 2 },
    stars: [],
    allowedBlocks: BASIC_LOOP,
    maxBlocks: 3,
    hint: '用循环(6次)包裹1个前进指令。',
  },
  {
    id: 'level-11',
    name: '第11关：循环转弯',
    description: '循环里可以放多个指令！',
    difficulty: 3,
    width: 5,
    height: 5,
    grid: makeGrid(5, 5),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 0, y: 0 },
    stars: [
      { x: 4, y: 0 },
      { x: 4, y: 4 },
      { x: 0, y: 4 },
    ],
    allowedBlocks: BASIC_LOOP,
    maxBlocks: 5,
    hint: '循环4次：前进4 + 右转。正方形路径！',
  },
  {
    id: 'level-12',
    name: '第12关：阶梯形',
    description: '用循环走阶梯形路径。',
    difficulty: 3,
    width: 6,
    height: 6,
    grid: makeGrid(6, 6),
    start: { x: 0, y: 5 },
    startDirection: 0,
    goal: { x: 5, y: 0 },
    stars: [
      { x: 1, y: 4 },
      { x: 2, y: 3 },
      { x: 3, y: 2 },
      { x: 4, y: 1 },
    ],
    allowedBlocks: BASIC_LOOP,
    maxBlocks: 5,
    hint: '循环5次：前进1 + 右转 + 前进1 + 左转',
  },
  {
    id: 'level-13',
    name: '第13关：墙迷宫',
    description: '更复杂的迷宫。',
    difficulty: 3,
    width: 7,
    height: 7,
    grid: makeGrid(7, 7, [
      [1, 0], [1, 1], [1, 2],
      [3, 2], [3, 3], [3, 4], [3, 5],
      [5, 0], [5, 1], [5, 2], [5, 3], [5, 4],
      [2, 5],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 2,
    goal: { x: 6, y: 6 },
    stars: [{ x: 2, y: 0 }],
    allowedBlocks: BASIC_LOOP,
    hint: '注意起始方向是向下！',
  },
  {
    id: 'level-14',
    name: '第14关：螺旋',
    description: '走一个螺旋形，收集所有星星。',
    difficulty: 3,
    width: 5,
    height: 5,
    grid: makeGrid(5, 5),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 2, y: 2 },
    stars: [
      { x: 4, y: 0 },
      { x: 4, y: 4 },
      { x: 0, y: 4 },
      { x: 0, y: 1 },
    ],
    allowedBlocks: BASIC_LOOP,
    hint: '外一圈用循环，内一圈再走。',
  },
  {
    id: 'level-15',
    name: '第15关：陷阱！',
    description: '小心陷阱，不要掉进去！',
    difficulty: 3,
    width: 5,
    height: 5,
    grid: makeGrid(
      5,
      5,
      [],
      [
        [2, 1],
        [2, 2],
        [2, 3],
      ]
    ),
    start: { x: 0, y: 2 },
    startDirection: 1,
    goal: { x: 4, y: 2 },
    stars: [],
    allowedBlocks: BASIC_LOOP,
    hint: '向上或向下绕过陷阱区域。',
  },
  {
    id: 'level-16',
    name: '第16关：如果是墙',
    description: '学习使用条件判断：如果前方是墙...',
    difficulty: 4,
    width: 6,
    height: 6,
    grid: makeGrid(6, 6, [
      [3, 0], [3, 1], [3, 2], [3, 3], [3, 4],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 5, y: 5 },
    stars: [{ x: 2, y: 5 }],
    allowedBlocks: CONDITION_BLOCKS,
    maxBlocks: 6,
    hint: '循环+条件：前进，若前方是墙则右转。',
  },
  {
    id: 'level-17',
    name: '第17关：如果有星',
    description: '检测前方是否有星星，然后决定动作。',
    difficulty: 4,
    width: 6,
    height: 5,
    grid: makeGrid(6, 5),
    start: { x: 0, y: 2 },
    startDirection: 1,
    goal: { x: 5, y: 2 },
    stars: [
      { x: 2, y: 2 },
      { x: 2, y: 0 },
      { x: 2, y: 4 },
      { x: 4, y: 2 },
    ],
    allowedBlocks: CONDITION_BLOCKS,
    maxBlocks: 8,
    hint: '思考如何用条件判断处理每行的星星。',
  },
  {
    id: 'level-18',
    name: '第18关：如果可走',
    description: '如果前方可以通行就前进，否则转弯。',
    difficulty: 4,
    width: 6,
    height: 6,
    grid: makeGrid(6, 6, [
      [1, 1], [2, 1], [3, 1],
      [3, 2], [3, 3],
      [1, 3], [2, 3],
      [1, 4], [1, 5],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 5, y: 5 },
    stars: [],
    allowedBlocks: CONDITION_BLOCKS,
    maxBlocks: 7,
    hint: '通用迷宫策略：能走就走，不能走就右转。',
  },
  {
    id: 'level-19',
    name: '第19关：星星通道',
    description: '通道上有多颗星星，全部收集。',
    difficulty: 4,
    width: 7,
    height: 5,
    grid: makeGrid(7, 5, [
      [0, 1], [0, 2], [0, 3],
      [6, 1], [6, 2], [6, 3],
      [2, 0], [2, 4],
      [4, 0], [4, 4],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 2,
    goal: { x: 6, y: 4 },
    stars: [
      { x: 0, y: 4 },
      { x: 1, y: 2 },
      { x: 3, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 0 },
    ],
    allowedBlocks: CONDITION_BLOCKS,
    hint: '用条件判断规划最优路径收集所有星星。',
  },
  {
    id: 'level-20',
    name: '第20关：大迷宫',
    description: '用条件指令和循环征服大迷宫！',
    difficulty: 4,
    width: 8,
    height: 8,
    grid: makeGrid(8, 8, [
      [1, 0], [1, 1], [1, 2], [3, 0], [3, 1],
      [3, 3], [3, 4], [3, 5], [5, 2], [5, 3],
      [5, 5], [5, 6], [5, 7], [2, 6], [3, 6],
      [6, 0], [6, 1], [7, 3], [7, 4], [0, 5],
      [0, 6], [0, 7], [1, 4],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 7, y: 7 },
    stars: [
      { x: 2, y: 0 },
      { x: 7, y: 0 },
      { x: 0, y: 4 },
    ],
    allowedBlocks: CONDITION_BLOCKS,
    hint: '使用"如果前方是墙就右转"的策略配合循环。',
  },
  {
    id: 'level-21',
    name: '第21关：第一个函数',
    description: '定义一个函数，让代码更整洁！',
    difficulty: 5,
    width: 7,
    height: 7,
    grid: makeGrid(7, 7),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 6, y: 6 },
    stars: [
      { x: 3, y: 0 },
      { x: 6, y: 3 },
      { x: 3, y: 6 },
      { x: 0, y: 3 },
    ],
    allowedBlocks: FUNCTION_BLOCKS,
    maxBlocks: 8,
    hint: '把"前进3+右转"定义成函数，然后调用4次。',
  },
  {
    id: 'level-22',
    name: '第22关：重复模式',
    description: '找到重复的模式，用函数简化！',
    difficulty: 5,
    width: 8,
    height: 5,
    grid: makeGrid(8, 5),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 7, y: 4 },
    stars: [
      { x: 1, y: 2 },
      { x: 3, y: 2 },
      { x: 5, y: 2 },
    ],
    allowedBlocks: FUNCTION_BLOCKS,
    maxBlocks: 8,
    hint: '观察规律：右1下2右1上2？不对，想想。',
  },
  {
    id: 'level-23',
    name: '第23关：之字形',
    description: '之字形路线上的星星都要收集。',
    difficulty: 5,
    width: 7,
    height: 7,
    grid: makeGrid(7, 7),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 6, y: 6 },
    stars: [
      { x: 2, y: 0 },
      { x: 2, y: 2 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 6, y: 4 },
    ],
    allowedBlocks: FUNCTION_BLOCKS,
    maxBlocks: 10,
    hint: '定义一个"右2+下2+右1..."的函数？',
  },
  {
    id: 'level-24',
    name: '第24关：嵌套循环',
    description: '循环里面还能放循环！',
    difficulty: 5,
    width: 5,
    height: 5,
    grid: makeGrid(5, 5),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 0, y: 0 },
    stars: [
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 2, y: 4 },
      { x: 0, y: 4 },
      { x: 0, y: 2 },
    ],
    allowedBlocks: FUNCTION_BLOCKS,
    maxBlocks: 7,
    hint: '外循环2次，每次包含前进4+右转+前进2+右转。',
  },
  {
    id: 'level-25',
    name: '第25关：墙阵',
    description: '穿过一排排的墙。',
    difficulty: 5,
    width: 9,
    height: 5,
    grid: makeGrid(9, 5, [
      [1, 0], [1, 1], [1, 3], [1, 4],
      [3, 0], [3, 2], [3, 3], [3, 4],
      [5, 1], [5, 2], [5, 3], [5, 4],
      [7, 0], [7, 1], [7, 2], [7, 4],
    ]),
    start: { x: 0, y: 2 },
    startDirection: 1,
    goal: { x: 8, y: 2 },
    stars: [
      { x: 2, y: 2 },
      { x: 4, y: 1 },
      { x: 6, y: 0 },
    ],
    allowedBlocks: CONDITION_BLOCKS,
    hint: '每2格遇到墙，找到穿过的缺口。',
  },
  {
    id: 'level-26',
    name: '第26关：交叉陷阱',
    description: '陷阱组成十字，小心绕行。',
    difficulty: 5,
    width: 7,
    height: 7,
    grid: makeGrid(
      7,
      7,
      [],
      [
        [3, 0], [3, 1], [3, 2],
        [0, 3], [1, 3], [2, 3], [4, 3], [5, 3], [6, 3],
        [3, 4], [3, 5], [3, 6],
      ]
    ),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 6, y: 6 },
    stars: [
      { x: 6, y: 0 },
      { x: 0, y: 6 },
    ],
    allowedBlocks: CONDITION_BLOCKS,
    maxBlocks: 12,
    hint: '十字陷阱把地图分成4块，绕大圈。',
  },
  {
    id: 'level-27',
    name: '第27关：函数+条件',
    description: '组合使用函数和条件判断。',
    difficulty: 6,
    width: 8,
    height: 8,
    grid: makeGrid(8, 8, [
      [2, 0], [2, 1], [2, 2],
      [4, 5], [4, 6], [4, 7],
      [6, 2], [6, 3], [6, 4],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 7, y: 7 },
    stars: [
      { x: 1, y: 0 },
      { x: 3, y: 4 },
      { x: 5, y: 6 },
      { x: 7, y: 3 },
    ],
    allowedBlocks: ALL_BLOCKS,
    maxBlocks: 12,
    hint: '定义处理障碍的函数，在主程序中调用。',
  },
  {
    id: 'level-28',
    name: '第28关：全面挑战',
    description: '所有指令都可以用，解决这个复杂关卡。',
    difficulty: 6,
    width: 9,
    height: 9,
    grid: makeGrid(9, 9, [
      [2, 0], [2, 1], [2, 2], [2, 3],
      [6, 5], [6, 6], [6, 7], [6, 8],
      [0, 5], [1, 5], [2, 5], [3, 5],
      [5, 3], [6, 3], [7, 3], [8, 3],
      [4, 0], [4, 1],
      [4, 7], [4, 8],
    ], [
      [4, 4],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 8, y: 8 },
    stars: [
      { x: 1, y: 0 },
      { x: 8, y: 0 },
      { x: 0, y: 8 },
      { x: 8, y: 5 },
      { x: 3, y: 8 },
    ],
    allowedBlocks: ALL_BLOCKS,
    hint: '先收集外围星星，再处理内部。',
  },
  {
    id: 'level-29',
    name: '第29关：终极迷宫',
    description: '终极迷宫挑战，证明你的编程能力！',
    difficulty: 6,
    width: 10,
    height: 10,
    grid: makeGrid(10, 10, [
      [1, 0], [1, 1], [3, 0], [3, 1], [3, 2],
      [5, 0], [5, 1], [7, 0], [7, 1], [7, 2], [7, 3],
      [2, 3], [2, 4], [2, 5], [4, 3], [4, 4],
      [5, 5], [5, 6], [5, 7], [5, 8],
      [0, 7], [1, 7], [2, 7], [3, 7],
      [7, 5], [7, 6], [9, 3], [9, 4], [9, 5],
      [8, 8], [8, 9], [6, 9],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 2,
    goal: { x: 9, y: 9 },
    stars: [
      { x: 2, y: 0 },
      { x: 6, y: 0 },
      { x: 0, y: 6 },
      { x: 4, y: 6 },
      { x: 9, y: 6 },
      { x: 7, y: 9 },
    ],
    allowedBlocks: ALL_BLOCKS,
    hint: '起始方向向下！用函数处理长直线路段。',
  },
  {
    id: 'level-30',
    name: '第30关：收集大师',
    description: '大量星星等你来收集！',
    difficulty: 6,
    width: 10,
    height: 10,
    grid: makeGrid(10, 10),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 0, y: 0 },
    stars: [
      { x: 3, y: 0 }, { x: 6, y: 0 }, { x: 9, y: 0 },
      { x: 0, y: 3 }, { x: 3, y: 3 }, { x: 6, y: 3 }, { x: 9, y: 3 },
      { x: 0, y: 6 }, { x: 3, y: 6 }, { x: 6, y: 6 }, { x: 9, y: 6 },
      { x: 0, y: 9 }, { x: 3, y: 9 }, { x: 6, y: 9 }, { x: 9, y: 9 },
    ],
    allowedBlocks: ALL_BLOCKS,
    maxBlocks: 15,
    hint: '网格状星星，用循环+函数遍历所有点。',
  },
  {
    id: 'level-31',
    name: '第31关：迷宫寻宝',
    description: '在迷宫中收集所有宝藏。',
    difficulty: 7,
    width: 11,
    height: 11,
    grid: makeGrid(11, 11, [
      [1, 1], [2, 1], [3, 1], [5, 1], [6, 1], [7, 1], [9, 1],
      [1, 3], [3, 3], [4, 3], [5, 3], [7, 3], [9, 3],
      [1, 4], [3, 4], [7, 4], [9, 4],
      [1, 5], [3, 5], [4, 5], [5, 5], [6, 5], [7, 5], [9, 5],
      [1, 7], [2, 7], [3, 7], [5, 7], [6, 7], [7, 7], [9, 7], [10, 7],
      [1, 9], [3, 9], [4, 9], [5, 9], [7, 9], [8, 9], [9, 9],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 10, y: 10 },
    stars: [
      { x: 4, y: 1 }, { x: 8, y: 1 },
      { x: 2, y: 4 }, { x: 6, y: 4 },
      { x: 2, y: 7 }, { x: 8, y: 7 },
      { x: 2, y: 9 }, { x: 6, y: 9 },
    ],
    allowedBlocks: ALL_BLOCKS,
    hint: '规划路径，用条件判断应对墙壁。',
  },
  {
    id: 'level-32',
    name: '第32关：蛇形收集',
    description: '像蛇一样蜿蜒前进，收集每颗星！',
    difficulty: 7,
    width: 8,
    height: 8,
    grid: makeGrid(8, 8),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 7, y: 7 },
    stars: [
      { x: 1, y: 0 }, { x: 3, y: 0 }, { x: 5, y: 0 }, { x: 7, y: 0 },
      { x: 6, y: 1 }, { x: 4, y: 1 }, { x: 2, y: 1 }, { x: 0, y: 1 },
      { x: 1, y: 2 }, { x: 3, y: 2 }, { x: 5, y: 2 }, { x: 7, y: 2 },
      { x: 6, y: 3 }, { x: 4, y: 3 }, { x: 2, y: 3 }, { x: 0, y: 3 },
      { x: 1, y: 4 }, { x: 3, y: 4 }, { x: 5, y: 4 }, { x: 7, y: 4 },
      { x: 6, y: 5 }, { x: 4, y: 5 }, { x: 2, y: 5 }, { x: 0, y: 5 },
      { x: 1, y: 6 }, { x: 3, y: 6 }, { x: 5, y: 6 }, { x: 7, y: 6 },
      { x: 6, y: 7 }, { x: 4, y: 7 }, { x: 2, y: 7 },
    ],
    allowedBlocks: ALL_BLOCKS,
    maxBlocks: 10,
    hint: '蛇形路径模式，用循环+函数。',
  },
  {
    id: 'level-33',
    name: '第33关：对角穿越',
    description: '从左上到右下，收集对角线的星星。',
    difficulty: 7,
    width: 9,
    height: 9,
    grid: makeGrid(9, 9, [
      [1, 0], [1, 2], [1, 4], [1, 6],
      [3, 1], [3, 3], [3, 5], [3, 7],
      [5, 0], [5, 2], [5, 4], [5, 6],
      [7, 1], [7, 3], [7, 5], [7, 7],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 8, y: 8 },
    stars: [
      { x: 0, y: 0 }, { x: 1, y: 1 }, { x: 2, y: 2 }, { x: 3, y: 3 },
      { x: 4, y: 4 }, { x: 5, y: 5 }, { x: 6, y: 6 }, { x: 7, y: 7 }, { x: 8, y: 8 },
    ],
    allowedBlocks: ALL_BLOCKS,
    maxBlocks: 8,
    hint: '走对角线：右1→下1，重复8次！',
  },
  {
    id: 'level-34',
    name: '第34关：陷阱迷宫',
    description: '到处都是陷阱，小心规划路线！',
    difficulty: 7,
    width: 8,
    height: 8,
    grid: makeGrid(
      8,
      8,
      [
        [0, 3], [1, 3],
        [6, 4], [7, 4],
        [3, 0], [4, 0],
        [3, 7], [4, 7],
      ],
      [
        [2, 2], [5, 2],
        [2, 5], [5, 5],
        [0, 0], [7, 0], [0, 7], [7, 7],
        [3, 3], [4, 4], [3, 4], [4, 3],
      ]
    ),
    start: { x: 1, y: 1 },
    startDirection: 1,
    goal: { x: 6, y: 6 },
    stars: [
      { x: 1, y: 4 },
      { x: 4, y: 1 },
      { x: 6, y: 2 },
      { x: 2, y: 6 },
    ],
    allowedBlocks: ALL_BLOCKS,
    maxBlocks: 15,
    hint: '起点在(1,1)不是角落！避开所有陷阱。',
  },
  {
    id: 'level-35',
    name: '第35关：终极挑战',
    description: '最终挑战！用你学到的一切完成它。',
    difficulty: 8,
    width: 12,
    height: 12,
    grid: makeGrid(12, 12, [
      [2, 0], [2, 1], [2, 2],
      [5, 3], [5, 4], [5, 5], [5, 6],
      [8, 0], [8, 1], [8, 2], [8, 7], [8, 8],
      [10, 4], [10, 5],
      [0, 8], [1, 8], [2, 8], [3, 8],
      [6, 9], [6, 10], [6, 11],
      [9, 10], [9, 11],
      [0, 5], [1, 5],
      [3, 10], [3, 11], [4, 11],
    ], [
      [4, 4], [7, 7],
      [0, 11], [11, 0],
      [11, 11],
    ]),
    start: { x: 0, y: 0 },
    startDirection: 1,
    goal: { x: 11, y: 11 },
    stars: [
      { x: 1, y: 0 }, { x: 4, y: 0 }, { x: 7, y: 1 },
      { x: 0, y: 3 }, { x: 3, y: 5 }, { x: 7, y: 4 }, { x: 11, y: 3 },
      { x: 2, y: 9 }, { x: 5, y: 10 }, { x: 8, y: 10 },
      { x: 10, y: 8 }, { x: 10, y: 11 },
    ],
    allowedBlocks: ALL_BLOCKS,
    hint: '终极关卡，善用函数和循环！加油！',
  },
];

export function getLevelById(id: string): Level | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function getLevelsByDifficulty(maxDifficulty: number): Level[] {
  return LEVELS.filter((l) => l.difficulty <= maxDifficulty);
}
